services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - ./CREATE_TABLES.sql:/tmp/CREATE_TABLES.sql

    ports:
      - "1433:1433"
    networks:
      - ces-network
  ces-api:
    image: ces-api:latest
    environment: 
      ASPNETCORE_ENVIRONMENT: "DEV"
      ConnectionString: "server=sqlserver,1433;user id=sa;password=SqlServer2019!database=ces;timeout=100;MultipleActiveResultSets=True;TrustServerCertificate=True;Trusted_Connection=True"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - ces-network

networks:
  ces-network:
    driver: bridge