version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    networks:
      - my-network
    ports:
      - "1433:1433"

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    networks:
      - my-network
    volumes:
      - ./crt.sql:/tmp/crt.sql
      - ./populate-tables.sql:/tmp/populate-tables.sql
      - ./init-sql.sh:/tmp/init-sql.sh
    command: /bin/bash ./tmp/init-sql.sh
  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - stack.templates.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   networks:
    - my-network
  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.17.0
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
   networks:
    - my-network
  
networks:
  my-network:
    driver: bridge
    
volumes:
  elasticsearch-data:   
      
