// <auto-generated />
using System;
using Ces.Api.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ces.Api.Migrations
{
    [DbContext(typeof(CesContext))]
    [Migration("20240324192421_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ces.Api.Business.Models.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("IdTipoPergunta")
                        .HasColumnType("int");

                    b.Property<int?>("NotaMaxima")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("TxtPergunta")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoPergunta");

                    b.ToTable("Pergunta", (string)null);
                });

            modelBuilder.Entity("Ces.Api.Business.Models.TipoPergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("TipoPergunta", (string)null);
                });

            modelBuilder.Entity("Ces.Api.Business.Models.Pergunta", b =>
                {
                    b.HasOne("Ces.Api.Business.Models.TipoPergunta", "TipoPergunta")
                        .WithMany("Perguntas")
                        .HasForeignKey("IdTipoPergunta")
                        .IsRequired();

                    b.Navigation("TipoPergunta");
                });

            modelBuilder.Entity("Ces.Api.Business.Models.TipoPergunta", b =>
                {
                    b.Navigation("Perguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
